const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const { storage } = require('../config/firebase');

const generateRTIPdf = async (rtiText, publicId) => {
  try {
    const pdfDoc  = await PDFDocument.create();
    const page    = pdfDoc.addPage([595, 842]);
    const font    = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();
    const margin = 50;
    let y = height - margin;

    // Title
    page.drawText('RIGHT TO INFORMATION APPLICATION', {
      x: margin, y, font: boldFont, size: 16, color: rgb(0.1, 0.1, 0.5),
    });
    y -= 30;
    page.drawText(`Ticket ID: ${publicId}`, { x: margin, y, font, size: 10, color: rgb(0.4, 0.4, 0.4) });
    y -= 20;

    // Draw a line
    page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
    y -= 20;

    // RTI text (word-wrapped)
    const lines = rtiText.split('\n');
    for (const line of lines) {
      if (y < margin + 50) {
        // New page if needed
        const newPage = pdfDoc.addPage([595, 842]);
        y = 842 - margin;
      }
      page.drawText(line.substring(0, 100), { x: margin, y, font, size: 10, color: rgb(0, 0, 0) });
      y -= 14;
    }

    // Footer
    page.drawText(`Generated by Community Hero on ${new Date().toDateString()}`, {
      x: margin, y: margin, font, size: 8, color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();
    const buffer   = Buffer.from(pdfBytes);

    // Upload to Firebase Storage
    const bucket  = storage.bucket();
    const path    = `reports/${publicId}/rti-${Date.now()}.pdf`;
    const file    = bucket.file(path);
    await file.save(buffer, { contentType: 'application/pdf' });
    await file.makePublic();

    return `https://storage.googleapis.com/${bucket.name}/${path}`;
  } catch (err) {
    console.error('[PDF] Generation failed:', err.message);
    return null;
  }
};

module.exports = { generateRTIPdf };
