// NOTE: These don't create Firebase Auth users — that's done via the admin UI.
// These are the Firestore officer profile documents only.
// UIDs are placeholders — replace with real Firebase Auth UIDs after creating accounts.

const officers = [
  {
    uid: 'officer_rajesh_001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@kmc.gov.in',
    designation: 'Junior Engineer',
    departmentId: 'roads_infrastructure',
    wardIds: ['Ward 82', 'Ward 83'],
    phone: '+919876543210',
    status: 'active',
    activeCaseCount: 3,
    totalAssigned: 47,
    resolvedCount: 38,
    ghostClosureCount: 1,
    overrideCount: 2,
    accountabilityScore: 85,
    performanceScore: 82,
    joinedAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'officer_priya_002',
    name: 'Priya Sharma',
    email: 'priya.sharma@kmc.gov.in',
    designation: 'Senior Engineer',
    departmentId: 'roads_infrastructure',
    wardIds: ['Ward 82', 'Ward 83', 'Ward 84'],
    phone: '+919876543211',
    status: 'active',
    activeCaseCount: 2,
    totalAssigned: 89,
    resolvedCount: 81,
    ghostClosureCount: 0,
    overrideCount: 1,
    accountabilityScore: 95,
    performanceScore: 93,
    joinedAt: new Date('2023-06-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'officer_suresh_003',
    name: 'Suresh Babu',
    email: 'suresh.babu@kmc.gov.in',
    designation: 'Inspector',
    departmentId: 'water_supply',
    wardIds: ['Ward 84', 'Ward 85'],
    phone: '+919876543212',
    status: 'active',
    activeCaseCount: 5,
    totalAssigned: 62,
    resolvedCount: 48,
    ghostClosureCount: 3,
    overrideCount: 4,
    accountabilityScore: 70,
    performanceScore: 75,
    joinedAt: new Date('2024-03-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'officer_meena_004',
    name: 'Meena Patel',
    email: 'meena.patel@kmc.gov.in',
    designation: 'Sub-Inspector',
    departmentId: 'sanitation',
    wardIds: ['Ward 82', 'Ward 84'],
    phone: '+919876543213',
    status: 'active',
    activeCaseCount: 1,
    totalAssigned: 33,
    resolvedCount: 30,
    ghostClosureCount: 0,
    overrideCount: 0,
    accountabilityScore: 100,
    performanceScore: 97,
    joinedAt: new Date('2024-07-20').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'officer_arun_005',
    name: 'Arun Singh',
    email: 'arun.singh@kmc.gov.in',
    designation: 'Electrician Grade 1',
    departmentId: 'electricity',
    wardIds: ['Ward 83', 'Ward 84', 'Ward 85'],
    phone: '+919876543214',
    status: 'active',
    activeCaseCount: 4,
    totalAssigned: 28,
    resolvedCount: 22,
    ghostClosureCount: 0,
    overrideCount: 1,
    accountabilityScore: 92,
    performanceScore: 88,
    joinedAt: new Date('2024-09-05').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'officer_kavita_006',
    name: 'Kavita Das',
    email: 'kavita.das@kmc.gov.in',
    designation: 'Junior Engineer',
    departmentId: 'roads_infrastructure',
    wardIds: ['Ward 85'],
    phone: '+919876543215',
    status: 'on_leave',
    activeCaseCount: 0,
    totalAssigned: 15,
    resolvedCount: 12,
    ghostClosureCount: 0,
    overrideCount: 0,
    accountabilityScore: 90,
    performanceScore: 88,
    joinedAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

module.exports = officers;
