const now = new Date();
const daysAgo = (d) => new Date(now - d * 86400000).toISOString();
const sla7 = (d) => new Date(now - (d - 7) * 86400000).toISOString();

const tickets = [
  // Ticket 1: UNASSIGNED — open manhole, severity 9 (top priority)
  {
    docId: 'KOL-2026-00149-a1b2c3',
    publicId: 'KOL-2026-00149',
    status: 'UNASSIGNED',
    issueType: 'open_manhole',
    category: 'Public_Safety',
    severity: 9,
    dangerLevel: 'critical',
    departmentId: 'roads_infrastructure',
    description: 'Open manhole cover at the intersection of Rashbehari Ave and Lake Road. Very dangerous for pedestrians at night.',
    citizenDescription: 'There is an open manhole at Rashbehari crossing. Kids almost fell in yesterday evening.',
    aiSuggested: {
      issueType: 'open_manhole',
      severity: 9,
      confidence: 95,
      reasoning: 'Open manhole with no barricade visible. Life-threatening risk identified.',
    },
    location: {
      geohash: 'tnje9un',
      lat: 22.5282,
      lng: 88.3639,
      ward: 'Ward 82',
      city: 'Kolkata',
      address: 'Rashbehari Avenue & Lake Road, Ward 82, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=800',
      resolution: null,
      reopen: [],
    },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: null,
    assignedOfficerName: null,
    slaDeadline: sla7(3),
    upvoteCount: 12,
    upvoterIds: ['u1','u2','u3','u4','u5','u6','u7','u8','u9','u10','u11','u12'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: false,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },

  // Ticket 2: IN PROGRESS — pothole, assigned to Rajesh Kumar
  {
    docId: 'KOL-2026-00142-d4e5f6',
    publicId: 'KOL-2026-00142',
    status: 'IN_PROGRESS',
    issueType: 'pothole',
    category: 'Infrastructure',
    severity: 7,
    dangerLevel: 'moderate',
    departmentId: 'roads_infrastructure',
    description: 'Large pothole on Gariahat Road near the bus stop. Vehicles are swerving dangerously.',
    citizenDescription: 'Big pothole near Gariahat bus stop. My auto-rickshaw tyre almost burst.',
    aiSuggested: {
      issueType: 'pothole',
      severity: 7,
      confidence: 92,
      reasoning: 'Large pothole visible with damage to road surface. Moderate to high severity.',
    },
    location: {
      geohash: 'tnje9us',
      lat: 22.5206,
      lng: 88.3692,
      ward: 'Ward 83',
      city: 'Kolkata',
      address: 'Gariahat Road, Near Bus Stop, Ward 83, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1612345710888-71ed3aee8bbb?w=800',
      resolution: null,
      reopen: [],
    },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: 'officer_rajesh_001',
    assignedOfficerName: 'Rajesh Kumar',
    internalNotes: 'Please prioritize — near school zone',
    slaDeadline: sla7(5),
    upvoteCount: 8,
    upvoterIds: ['u1','u2','u3','u4','u5','u6','u7','u8'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: false,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },

  // Ticket 3: RESOLVED — ghost window open (for demo)
  {
    docId: 'KOL-2026-00138-g7h8i9',
    publicId: 'KOL-2026-00138',
    status: 'RESOLVED',
    issueType: 'broken_light',
    category: 'Electricity',
    severity: 5,
    dangerLevel: 'moderate',
    departmentId: 'electricity',
    description: 'Street light at Ballygunge Circular Road completely dark for 3 nights.',
    citizenDescription: 'The streetlight near my house has been out for 3 nights. Very dark and unsafe.',
    aiSuggested: {
      issueType: 'broken_light',
      severity: 5,
      confidence: 88,
      reasoning: 'Broken streetlight in residential area. Moderate safety concern.',
    },
    location: {
      geohash: 'tnje9uu',
      lat: 22.5141,
      lng: 88.3720,
      ward: 'Ward 83',
      city: 'Kolkata',
      address: 'Ballygunge Circular Road, Ward 83, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      resolution: 'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=800',
      reopen: [],
    },
    citizenId: 'citizen_priya_002',
    citizenPhone: '+919800000002',
    citizenEmail: 'priya.citizen@example.com',
    assignedOfficerId: 'officer_arun_005',
    assignedOfficerName: 'Arun Singh',
    internalNotes: '',
    slaDeadline: sla7(8),
    upvoteCount: 3,
    upvoterIds: ['u1','u2','u3'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2'],
    ghostWindowOpen: true,
    ghostWindowExpiry: new Date(now.getTime() + 7 * 86400000).toISOString(),
    resolvedAt: daysAgo(1),
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: true,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: false,
    evidenceReport: {
      officerId: 'officer_arun_005',
      submittedAt: daysAgo(1),
      beforePhotoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=800',
      geminiConfidence: 89,
      sameLocation: true,
      issueResolved: true,
      rejectionReason: null,
      approved: true,
    },
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },

  // Ticket 4: GHOST_FLAGGED — demo ghost detection
  {
    docId: 'KOL-2026-00133-j0k1l2',
    publicId: 'KOL-2026-00133',
    status: 'GHOST_FLAGGED',
    issueType: 'garbage',
    category: 'Sanitation',
    severity: 6,
    dangerLevel: 'moderate',
    departmentId: 'sanitation',
    description: 'Garbage dump near Jodhpur Park that was supposedly cleared has reappeared.',
    citizenDescription: 'Suresh marked this resolved but the garbage is back the next day!',
    aiSuggested: {
      issueType: 'garbage',
      severity: 6,
      confidence: 78,
      reasoning: 'Accumulated garbage visible. Health hazard classification applied.',
    },
    location: {
      geohash: 'tnje9uv',
      lat: 22.5090,
      lng: 88.3758,
      ward: 'Ward 84',
      city: 'Kolkata',
      address: 'Jodhpur Park Crossing, Ward 84, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800',
      resolution: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      reopen: ['https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800'],
    },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: 'officer_suresh_003',
    assignedOfficerName: 'Suresh Babu',
    internalNotes: 'GHOST DETECTED: Officer marked resolved but issue reappeared next day.',
    slaDeadline: daysAgo(-4),
    upvoteCount: 15,
    upvoterIds: ['u1','u2','u3','u4','u5','u6','u7','u8','u9','u10','u11','u12','u13','u14','u15'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    resolvedAt: daysAgo(5),
    ghostCount: 1,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: true,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: true,
    ghostReport: {
      issue_still_present: true,
      confidence: 91,
      decision: 'reject_resolution',
      reason: 'Garbage has reaccumulated at the same location within 24 hours of claimed resolution.',
      comparison: {
        image1_shows: 'Large pile of garbage at same location as original report',
        image2_shows: 'Same location with garbage dump',
        image3_shows: 'Area appears briefly cleared',
        conclusion: 'Resolution was superficial — garbage was not properly disposed',
      }
    },
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },

  // Ticket 5: ESCALATED — waterlogging
  {
    docId: 'KOL-2026-00128-m3n4o5',
    publicId: 'KOL-2026-00128',
    status: 'ESCALATED',
    issueType: 'waterlogging',
    category: 'Water_Drainage',
    severity: 8,
    dangerLevel: 'critical',
    departmentId: 'water_supply',
    description: 'Severe waterlogging at Tollygunge Metro crossing. Water level knee-deep during rain.',
    citizenDescription: 'Water up to knee level near metro gate during last rain. Very dangerous.',
    aiSuggested: {
      issueType: 'waterlogging',
      severity: 8,
      confidence: 94,
      reasoning: 'Severe waterlogging in urban area. High severity during monsoon season.',
    },
    location: {
      geohash: 'tnje9uw',
      lat: 22.4949,
      lng: 88.3526,
      ward: 'Ward 85',
      city: 'Kolkata',
      address: 'Tollygunge Metro Gate 1, Ward 85, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1547393429-0f3b28e87beb?w=800',
      resolution: null,
      reopen: [],
    },
    citizenId: 'citizen_priya_002',
    citizenPhone: '+919800000002',
    citizenEmail: 'priya.citizen@example.com',
    assignedOfficerId: 'officer_suresh_003',
    assignedOfficerName: 'Suresh Babu',
    internalNotes: 'Auto-escalated after 14 days. Requires senior officer review.',
    slaDeadline: daysAgo(7),
    upvoteCount: 24,
    upvoterIds: Array.from({length:24},(_,i)=>`u${i+1}`),
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: true,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: true,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(4),
  },

  // Ticket 6: RTI_FILED — 33 days old sewage overflow
  {
    docId: 'KOL-2026-00101-p6q7r8',
    publicId: 'KOL-2026-00101',
    status: 'RTI_FILED',
    issueType: 'sewage_overflow',
    category: 'Sanitation',
    severity: 8,
    dangerLevel: 'critical',
    departmentId: 'sanitation',
    description: 'Sewage overflowing onto the street near Kalighat Temple. Health emergency.',
    citizenDescription: 'Sewage is overflowing onto the road. Terrible smell. Kids getting sick.',
    aiSuggested: {
      issueType: 'sewage_overflow',
      severity: 8,
      confidence: 96,
      reasoning: 'Active sewage overflow detected. Critical health and sanitation emergency.',
    },
    location: {
      geohash: 'tnje9ux',
      lat: 22.5274,
      lng: 88.3435,
      ward: 'Ward 82',
      city: 'Kolkata',
      address: 'Near Kalighat Temple, Ward 82, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=800',
      resolution: null,
      reopen: [],
    },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: 'officer_meena_004',
    assignedOfficerName: 'Meena Patel',
    internalNotes: 'RTI auto-generated on Day 30. Not yet resolved.',
    slaDeadline: daysAgo(26),
    upvoteCount: 31,
    upvoterIds: Array.from({length:31},(_,i)=>`u${i+1}`),
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 2,
    reminderSent: true,
    rtiGenerated: true,
    rtiText: 'RTI Application generated for KOL-2026-00101. See PDF link.',
    rtiPdfUrl: 'https://storage.googleapis.com/community-hero.appspot.com/reports/KOL-2026-00101/rti-demo.pdf',
    appealGenerated: false,
    slaBreached: true,
    createdAt: daysAgo(33),
    updatedAt: daysAgo(3),
  },

  // Ticket 7: CLOSED_OVERRIDE — waterlogging
  {
    docId: 'KOL-2026-00115-s9t0u1',
    publicId: 'KOL-2026-00115',
    status: 'CLOSED_OVERRIDE',
    issueType: 'waterlogging',
    category: 'Water_Drainage',
    severity: 6,
    dangerLevel: 'moderate',
    departmentId: 'water_supply',
    description: 'Waterlogging at Jadavpur crossroads after rain.',
    citizenDescription: 'Water logging near jadavpur cross. Not that bad but still.',
    aiSuggested: { issueType: 'waterlogging', severity: 6, confidence: 72 },
    location: {
      geohash: 'tnje9uy',
      lat: 22.5037,
      lng: 88.3720,
      ward: 'Ward 84',
      city: 'Kolkata',
      address: 'Jadavpur Crossroads, Ward 84, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1547393429-0f3b28e87beb?w=800',
      resolution: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      reopen: [],
    },
    citizenId: 'citizen_priya_002',
    citizenPhone: '+919800000002',
    citizenEmail: 'priya.citizen@example.com',
    assignedOfficerId: 'officer_suresh_003',
    assignedOfficerName: 'Suresh Babu',
    internalNotes: 'Closed with override — temporary condition during monsoon.',
    slaDeadline: daysAgo(15),
    upvoteCount: 4,
    upvoterIds: ['u1','u2','u3','u4'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    resolvedAt: daysAgo(10),
    ghostCount: 0,
    overrideCount: 1,
    resolutionRetries: 1,
    reminderSent: true,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: true,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(10),
  },

  // ── DEMO: Aged ticket — 31 days, ESCALATED, RTI NOT YET FILED ──────────
  // Pressing "Run SLA Check Now" will fire the RTI agent on this ticket live.
  {
    docId: 'KOL-2026-00090-demo30',
    publicId: 'KOL-2026-00090',
    status: 'ESCALATED',
    issueType: 'broken_road',
    category: 'Infrastructure',
    severity: 7,
    dangerLevel: 'moderate',
    departmentId: 'roads_infrastructure',
    description: 'Large section of road surface collapsed near Dhakuria Bridge. Vehicles swerving dangerously and minor accidents reported.',
    citizenDescription: 'Road is broken near Dhakuria bridge. Vehicles swerving, 2 accidents already.',
    aiSuggested: { issueType: 'broken_road', severity: 7, confidence: 91, reasoning: 'Significant road damage creating traffic hazard.' },
    location: {
      geohash: 'tnje9ua',
      lat: 22.5168,
      lng: 88.3669,
      ward: 'Ward 83',
      city: 'Kolkata',
      address: 'Dhakuria Bridge Road, Ward 83, Kolkata',
    },
    photos: { report: 'https://images.unsplash.com/photo-1612345710888-71ed3aee8bbb?w=800', resolution: null, reopen: [] },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: 'officer_priya_002',
    assignedOfficerName: 'Priya Sharma',
    internalNotes: 'Auto-escalated at day 14. No resolution after 31 days.',
    slaDeadline: daysAgo(24),
    upvoteCount: 19,
    upvoterIds: Array.from({length:19},(_,i)=>`u${i+1}`),
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: true,
    rtiGenerated: false,   // ← RTI NOT YET FILED — agent will file it when triggered
    appealGenerated: false,
    slaBreached: true,
    probableDuplicateOf: '',
    createdAt: daysAgo(31),
    updatedAt: daysAgo(2),
  },

  // ── DEMO: Aged ticket — 62 days, RTI already filed, APPEAL pending ──────
  // Pressing "Run SLA Check Now" will fire the appeal agent on this ticket.
  {
    docId: 'KOL-2026-00058-demo62',
    publicId: 'KOL-2026-00058',
    status: 'RTI_FILED',
    issueType: 'illegal_dumping',
    category: 'Environment',
    severity: 8,
    dangerLevel: 'critical',
    departmentId: 'environment',
    description: 'Industrial waste illegally dumped in East Kolkata Wetlands. Water contamination risk for thousands of families downstream.',
    citizenDescription: 'Toxic waste dumped in wetlands. Water smells terrible. Kids cannot play near the area.',
    aiSuggested: { issueType: 'illegal_dumping', severity: 8, confidence: 97, reasoning: 'Illegal industrial dumping — environmental emergency with public health implications.' },
    location: {
      geohash: 'tnjeb00',
      lat: 22.5465,
      lng: 88.4312,
      ward: 'Ward 58',
      city: 'Kolkata',
      address: 'East Kolkata Wetlands, Near Dhapa, Ward 58, Kolkata',
    },
    photos: { report: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800', resolution: null, reopen: [] },
    citizenId: 'citizen_priya_002',
    citizenPhone: '+919800000002',
    citizenEmail: 'priya.citizen@example.com',
    assignedOfficerId: 'officer_suresh_003',
    assignedOfficerName: 'Suresh Babu',
    internalNotes: 'RTI filed at Day 30. First appeal due at Day 60. Environmentally critical.',
    slaDeadline: daysAgo(55),
    upvoteCount: 47,
    upvoterIds: Array.from({length:47},(_,i)=>`u${i+1}`),
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2','v3'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 3,
    reminderSent: true,
    rtiGenerated: true,
    rtiText: 'RTI Application under Section 6 of Right to Information Act, 2005 — Filed for KOL-2026-00058 (Illegal Industrial Dumping, East Kolkata Wetlands). CPIO directed to provide action taken report within 30 days.',
    rtiPdfUrl: null,
    appealGenerated: false,   // ← APPEAL NOT YET FILED — agent will file when triggered
    slaBreached: true,
    probableDuplicateOf: '',
    createdAt: daysAgo(62),
    updatedAt: daysAgo(5),
  },

  // ── DEMO: Probable duplicate — citizen force-submitted over an existing report ──
  {
    docId: 'KOL-2026-00152-demo-dup',
    publicId: 'KOL-2026-00152',
    status: 'UNASSIGNED',
    issueType: 'pothole',
    category: 'Infrastructure',
    severity: 6,
    dangerLevel: 'moderate',
    departmentId: 'roads_infrastructure',
    description: 'Pothole on Brabourne road near Lake Town junction. Road is broken and water collects there.',
    citizenDescription: 'Bad pothole near Lake Town. Makes loud noise when vehicles pass.',
    aiSuggested: { issueType: 'pothole', severity: 6, confidence: 88, reasoning: 'Pothole on urban road.' },
    location: {
      geohash: 'tnje9up',
      lat: 22.5882,
      lng: 88.3906,
      ward: 'Ward 34',
      city: 'Kolkata',
      address: 'Brabourn road, Lake Town, Kolkata',
    },
    photos: { report: 'https://images.unsplash.com/photo-1612345710888-71ed3aee8bbb?w=800', resolution: null, reopen: [] },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: null,
    assignedOfficerName: null,
    internalNotes: '',
    slaDeadline: sla7(1),
    upvoteCount: 0,
    upvoterIds: [],
    verificationStatus: 'PENDING',
    verifierIds: [],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: false,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: false,
    probableDuplicateOf: 'KOL-2026-00151',
    duplicateMatchConfidence: 82,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // Ticket 8: ASSIGNED — water leakage
  {
    docId: 'KOL-2026-00145-v2w3x4',
    publicId: 'KOL-2026-00145',
    status: 'ASSIGNED',
    issueType: 'water_leakage',
    category: 'Water_Drainage',
    severity: 5,
    dangerLevel: 'moderate',
    departmentId: 'water_supply',
    description: 'Water main leakage at Exide crossing causing road damage and water waste.',
    citizenDescription: 'Water leaking from pipe underground near exide. Wasting so much water!',
    aiSuggested: { issueType: 'water_leakage', severity: 5, confidence: 83 },
    location: {
      geohash: 'tnje9uz',
      lat: 22.5349,
      lng: 88.3504,
      ward: 'Ward 82',
      city: 'Kolkata',
      address: 'Exide Crossing, Sarat Bose Road, Ward 82, Kolkata',
    },
    photos: {
      report: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800',
      resolution: null,
      reopen: [],
    },
    citizenId: 'citizen_arjun_001',
    citizenPhone: '+919800000001',
    citizenEmail: 'arjun.citizen@example.com',
    assignedOfficerId: 'officer_suresh_003',
    assignedOfficerName: 'Suresh Babu',
    internalNotes: '',
    slaDeadline: sla7(2),
    upvoteCount: 6,
    upvoterIds: ['u1','u2','u3','u4','u5','u6'],
    verificationStatus: 'VERIFIED',
    verifierIds: ['v1','v2'],
    ghostWindowOpen: false,
    ghostWindowExpiry: null,
    ghostCount: 0,
    overrideCount: 0,
    resolutionRetries: 0,
    reminderSent: false,
    rtiGenerated: false,
    appealGenerated: false,
    slaBreached: false,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
];

module.exports = tickets;
