const wardStats = [
  {
    id: 'ward_82',
    ward: 'Ward 82',
    city: 'Kolkata',
    totalReported: 47,
    totalResolved: 31,
    totalPending: 16,
    healthScore: 66,
    healthGrade: 'C+',
    topIssues: ['pothole','waterlogging','garbage'],
    avgResolutionDays: 9.2,
    activeOfficers: 3,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ward_83',
    ward: 'Ward 83',
    city: 'Kolkata',
    totalReported: 38,
    totalResolved: 30,
    totalPending: 8,
    healthScore: 79,
    healthGrade: 'B+',
    topIssues: ['pothole','broken_light','damaged_road'],
    avgResolutionDays: 7.5,
    activeOfficers: 2,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ward_84',
    ward: 'Ward 84',
    city: 'Kolkata',
    totalReported: 52,
    totalResolved: 46,
    totalPending: 6,
    healthScore: 88,
    healthGrade: 'A-',
    topIssues: ['garbage','sewage_overflow','waterlogging'],
    avgResolutionDays: 6.1,
    activeOfficers: 3,
    lastUpdated: new Date().toISOString(),
  },
];

module.exports = wardStats;
